import turtle
turtle.title("PFP By AvarageMilkEnjoyer")
turtle.begin_fill()
turtle.pensize(5)   
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.end_fill()
turtle.penup()
turtle.goto(30,1)
turtle.color("green")
turtle.pensize(8)   
turtle.rt(180)
turtle.fd(20)
turtle.pendown()
turtle.fd(28)
# Next
turtle.penup()
turtle.goto(60,1) 
turtle.fd(20)
turtle.pendown()
turtle.fd(28)
# Smile
turtle.penup()
turtle.goto(20, -70)
turtle.pendown()
turtle.left(180)
turtle.goto(20, -80)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(10)
turtle.penup()
turtle.goto(50, 50)

turtle.write("PFP By AvarageMilkEnjoyer :)") 

turtle.mainloop()
